-- MySQL Script generated by MySQL Workbench
-- Fri 10 Sep 2021 01:27:02 AM +07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema FirsProject_F11_N12
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema FirsProject_F11_N12
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FirsProject_F11_N12` ;
USE `FirsProject_F11_N12` ;

-- -----------------------------------------------------
-- Table `FirsProject_F11_N12`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FirsProject_F11_N12`.`USER` (
  `Id` VARCHAR(36) NOT NULL,
  `UserName` VARCHAR(30) NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  `Age` INT NULL DEFAULT NULL,
  `Email` VARCHAR(100) NULL DEFAULT NULL,
  `Phone` VARCHAR(20) NULL DEFAULT NULL,
  `Address` VARCHAR(500) NULL DEFAULT NULL,
  `IsActive` INT NULL DEFAULT NULL,
  `CreateBy` TIMESTAMP(4) NULL DEFAULT NULL,
  `CreateAt` TIMESTAMP(4) NULL DEFAULT NULL,
  `UpdateAt` TIMESTAMP(4) NULL DEFAULT NULL,
  `UpdateBy` TIMESTAMP(4) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FirsProject_F11_N12`.`CUSTOMER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FirsProject_F11_N12`.`CUSTOMER` (
  `Id` VARCHAR(36) NOT NULL,
  `UserID` VARCHAR(36) NULL DEFAULT NULL,
  `PaymentMethod` INT NOT NULL,
  `IsActive` INT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `UserID` (`UserID` ASC),
  CONSTRAINT `CUSTOMER_ibfk_1`
    FOREIGN KEY (`UserID`)
    REFERENCES `FirsProject_F11_N12`.`USER` (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FirsProject_F11_N12`.`ORDER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FirsProject_F11_N12`.`ORDER` (
  `Id` VARCHAR(36) NOT NULL,
  `CustomerId` VARCHAR(36) NULL DEFAULT NULL,
  `Price` DOUBLE(12,2) NULL DEFAULT NULL,
  `Tax` DOUBLE(12,2) NULL DEFAULT NULL,
  `Phone` VARCHAR(20) NULL DEFAULT NULL,
  `discount` DOUBLE(12,2) NULL DEFAULT NULL,
  `totalPrice` DOUBLE(12,2) NULL DEFAULT NULL,
  `IsDeleted` INT NULL DEFAULT NULL,
  `CreateBy` TIMESTAMP(4) NULL DEFAULT NULL,
  `CreateAt` TIMESTAMP(4) NULL DEFAULT NULL,
  `UpdateAt` TIMESTAMP(4) NULL DEFAULT NULL,
  `UpdateBy` TIMESTAMP(4) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `CustomerId` (`CustomerId` ASC),
  CONSTRAINT `ORDER_ibfk_1`
    FOREIGN KEY (`CustomerId`)
    REFERENCES `FirsProject_F11_N12`.`CUSTOMER` (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FirsProject_F11_N12`.`PRODUCT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FirsProject_F11_N12`.`PRODUCT` (
  `Id` VARCHAR(36) NOT NULL,
  `name` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(4000) NULL DEFAULT NULL,
  `Price` DOUBLE(12,2) NULL DEFAULT NULL,
  `Tax` DOUBLE(12,2) NULL DEFAULT NULL,
  `Phone` VARCHAR(20) NULL DEFAULT NULL,
  `discount` DOUBLE(12,2) NULL DEFAULT NULL,
  `totalPrice` DOUBLE(12,2) NULL DEFAULT NULL,
  `IsDeleted` INT NULL DEFAULT NULL,
  `CreateBy` TIMESTAMP(4) NULL DEFAULT NULL,
  `CreateAt` TIMESTAMP(4) NULL DEFAULT NULL,
  `UpdateAt` TIMESTAMP(4) NULL DEFAULT NULL,
  `UpdateBy` TIMESTAMP(4) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `name` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FirsProject_F11_N12`.`ORDER_DETAIL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FirsProject_F11_N12`.`ORDER_DETAIL` (
  `Id` VARCHAR(36) NOT NULL,
  `OrderId` VARCHAR(36) NULL DEFAULT NULL,
  `ProductId` VARCHAR(36) NULL DEFAULT NULL,
  `Price` DOUBLE(12,2) NULL DEFAULT NULL,
  `Tax` DOUBLE(12,2) NULL DEFAULT NULL,
  `Phone` VARCHAR(20) NULL DEFAULT NULL,
  `discount` DOUBLE(12,2) NULL DEFAULT NULL,
  `totalPrice` DOUBLE(12,2) NULL DEFAULT NULL,
  `IsDeleted` INT NULL DEFAULT NULL,
  `CreateBy` TIMESTAMP(4) NULL DEFAULT NULL,
  `CreateAt` TIMESTAMP(4) NULL DEFAULT NULL,
  `UpdateAt` TIMESTAMP(4) NULL DEFAULT NULL,
  `UpdateBy` TIMESTAMP(4) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `OrderId` (`OrderId` ASC, `ProductId` ASC),
  INDEX `ProductId` (`ProductId` ASC),
  CONSTRAINT `ORDER_DETAIL_ibfk_1`
    FOREIGN KEY (`OrderId`)
    REFERENCES `FirsProject_F11_N12`.`ORDER` (`Id`),
  CONSTRAINT `ORDER_DETAIL_ibfk_2`
    FOREIGN KEY (`ProductId`)
    REFERENCES `FirsProject_F11_N12`.`PRODUCT` (`Id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
